name: two_stroke_stuff
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.28.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.18
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
